# Generated by Django 4.1.3 on 2022-11-17 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jamapp', '0003_genre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, unique=True)),
                ('created', models.DateTimeField()),
                ('Total_songs', models.IntegerField()),
            ],
        ),
    ]
