# Generated by Django 4.1.3 on 2022-11-18 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jamapp', '0005_song_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='songs',
            field=models.ManyToManyField(to='jamapp.song'),
        ),
    ]
