# Generated by Django 4.1.3 on 2022-11-18 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jamapp', '0006_album_songs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='title',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
