# Generated by Django 4.1.3 on 2022-11-18 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jamapp', '0007_alter_song_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='songs',
            field=models.ManyToManyField(to='jamapp.song'),
        ),
        migrations.AlterField(
            model_name='album',
            name='songs',
            field=models.ManyToManyField(related_name='albums', to='jamapp.song'),
        ),
    ]
