# Generated by Django 4.1.3 on 2022-11-18 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jamapp', '0008_playlist_songs_alter_album_songs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('description', models.CharField(max_length=200, unique=True)),
                ('age', models.IntegerField()),
            ],
        ),
    ]
